// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void evButton1Released(lv_event_t * e);
void evButton2Released(lv_event_t * e);
void evButton3Released(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
