// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#ifndef UI_PAGEHAUPTBILD_H
#define UI_PAGEHAUPTBILD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_pagehauptbild
extern void ui_pagehauptbild_screen_init(void);
extern void ui_pagehauptbild_screen_destroy(void);
extern lv_obj_t * ui_pagehauptbild;
extern lv_obj_t * ui_panel1;
extern lv_obj_t * ui_lblversion;
extern lv_obj_t * ui_panel2;
extern lv_obj_t * ui_panel3;
extern void ui_event_btntarieren(lv_event_t * e);
extern lv_obj_t * ui_btntarieren;
extern lv_obj_t * ui_lbltarieren;
extern void ui_event_btnstart(lv_event_t * e);
extern lv_obj_t * ui_btnstart;
extern lv_obj_t * ui_lblstart;
extern void ui_event_btnartikel(lv_event_t * e);
extern lv_obj_t * ui_btnartikel;
extern lv_obj_t * ui_lblrezept;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

