// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#include "ui.h"

lv_obj_t * ui_pagehauptbild = NULL;
lv_obj_t * ui_panel1 = NULL;
lv_obj_t * ui_lblversion = NULL;
lv_obj_t * ui_panel2 = NULL;
lv_obj_t * ui_panel3 = NULL;
lv_obj_t * ui_btntarieren = NULL;
lv_obj_t * ui_lbltarieren = NULL;
lv_obj_t * ui_btnstart = NULL;
lv_obj_t * ui_lblstart = NULL;
lv_obj_t * ui_btnartikel = NULL;
lv_obj_t * ui_lblrezept = NULL;
// event funtions
void ui_event_btntarieren(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        evButton1Released(e);
    }
}

void ui_event_btnstart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        evButton2Released(e);
    }
}

void ui_event_btnartikel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        evButton3Released(e);
    }
}

// build funtions

void ui_pagehauptbild_screen_init(void)
{
    ui_pagehauptbild = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_pagehauptbild, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pagehauptbild, lv_color_hex(0x010824), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pagehauptbild, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel1 = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_panel1, 384);
    lv_obj_set_height(ui_panel1, 368);
    lv_obj_set_x(ui_panel1, 10);
    lv_obj_set_y(ui_panel1, 9);
    lv_obj_remove_flag(ui_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel1, lv_color_hex(0x010824), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel1, lv_color_hex(0x606164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblversion = lv_label_create(ui_panel1);
    lv_obj_set_width(ui_lblversion, 370);
    lv_obj_set_height(ui_lblversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblversion, 0);
    lv_obj_set_y(ui_lblversion, -155);
    lv_obj_set_align(ui_lblversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblversion, "PLACEHOLDER");
    lv_obj_set_style_text_color(ui_lblversion, lv_color_hex(0xF5FD04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblversion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblversion, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel2 = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_panel2, 384);
    lv_obj_set_height(ui_panel2, 180);
    lv_obj_set_x(ui_panel2, 405);
    lv_obj_set_y(ui_panel2, 9);
    lv_obj_remove_flag(ui_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel2, lv_color_hex(0x010824), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel2, lv_color_hex(0x606164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel3 = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_panel3, 384);
    lv_obj_set_height(ui_panel3, 176);
    lv_obj_set_x(ui_panel3, 405);
    lv_obj_set_y(ui_panel3, 201);
    lv_obj_remove_flag(ui_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel3, lv_color_hex(0x010824), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel3, lv_color_hex(0x606164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btntarieren = lv_button_create(ui_pagehauptbild);
    lv_obj_set_width(ui_btntarieren, 240);
    lv_obj_set_height(ui_btntarieren, 64);
    lv_obj_set_x(ui_btntarieren, 30);
    lv_obj_set_y(ui_btntarieren, 394);
    lv_obj_add_flag(ui_btntarieren, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btntarieren, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_btntarieren, lv_color_hex(0x01104A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btntarieren, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btntarieren, lv_color_hex(0x6C6969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btntarieren, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btntarieren, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btntarieren, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btntarieren, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btntarieren, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btntarieren, lv_color_hex(0x042ABC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btntarieren, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lbltarieren = lv_label_create(ui_btntarieren);
    lv_obj_set_width(ui_lbltarieren, 200);
    lv_obj_set_height(ui_lbltarieren, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltarieren, 1);
    lv_obj_set_y(ui_lbltarieren, -6);
    lv_label_set_text(ui_lbltarieren, "Button 1");
    lv_obj_set_style_text_color(ui_lbltarieren, lv_color_hex(0x365DF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbltarieren, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbltarieren, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbltarieren, &ui_font_Calibri48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnstart = lv_button_create(ui_pagehauptbild);
    lv_obj_set_width(ui_btnstart, 240);
    lv_obj_set_height(ui_btnstart, 64);
    lv_obj_set_x(ui_btnstart, 280);
    lv_obj_set_y(ui_btnstart, 394);
    lv_obj_add_flag(ui_btnstart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnstart, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_btnstart, lv_color_hex(0x01104A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnstart, lv_color_hex(0x6C6969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnstart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnstart, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnstart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnstart, lv_color_hex(0x042ABC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblstart = lv_label_create(ui_btnstart);
    lv_obj_set_width(ui_lblstart, 200);
    lv_obj_set_height(ui_lblstart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblstart, 1);
    lv_obj_set_y(ui_lblstart, -6);
    lv_label_set_text(ui_lblstart, "Button 2");
    lv_obj_set_style_text_color(ui_lblstart, lv_color_hex(0x365DF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblstart, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblstart, &ui_font_Calibri48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnartikel = lv_button_create(ui_pagehauptbild);
    lv_obj_set_width(ui_btnartikel, 240);
    lv_obj_set_height(ui_btnartikel, 64);
    lv_obj_set_x(ui_btnartikel, 530);
    lv_obj_set_y(ui_btnartikel, 394);
    lv_obj_add_flag(ui_btnartikel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnartikel, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_btnartikel, lv_color_hex(0x01104A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnartikel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnartikel, lv_color_hex(0x6C6969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnartikel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnartikel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnartikel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnartikel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnartikel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnartikel, lv_color_hex(0x042ABC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnartikel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblrezept = lv_label_create(ui_btnartikel);
    lv_obj_set_width(ui_lblrezept, 200);
    lv_obj_set_height(ui_lblrezept, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblrezept, 1);
    lv_obj_set_y(ui_lblrezept, -6);
    lv_label_set_text(ui_lblrezept, "Button 3");
    lv_obj_set_style_text_color(ui_lblrezept, lv_color_hex(0x365DF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblrezept, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblrezept, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblrezept, &ui_font_Calibri48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btntarieren, ui_event_btntarieren, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnstart, ui_event_btnstart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnartikel, ui_event_btnartikel, LV_EVENT_ALL, NULL);

}

void ui_pagehauptbild_screen_destroy(void)
{
    if(ui_pagehauptbild) lv_obj_del(ui_pagehauptbild);

    // NULL screen variables
    ui_pagehauptbild = NULL;
    ui_panel1 = NULL;
    ui_lblversion = NULL;
    ui_panel2 = NULL;
    ui_panel3 = NULL;
    ui_btntarieren = NULL;
    ui_lbltarieren = NULL;
    ui_btnstart = NULL;
    ui_lblstart = NULL;
    ui_btnartikel = NULL;
    ui_lblrezept = NULL;

}
