// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#ifndef _DISPLAY_UI_H
#define _DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_pagehauptbild.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_leds_led_rs_green_l_png);    // assets/LEDS/LED_RS_GREEN_L.png
LV_IMG_DECLARE(ui_img_leds_led_rs_red_l_png);    // assets/LEDS/LED_RS_RED_L.png

// FONTS
LV_FONT_DECLARE(ui_font_Calibri12);
LV_FONT_DECLARE(ui_font_Calibri12Bold);
LV_FONT_DECLARE(ui_font_Calibri16);
LV_FONT_DECLARE(ui_font_Calibri16Bold);
LV_FONT_DECLARE(ui_font_Calibri20);
LV_FONT_DECLARE(ui_font_Calibri20Bold);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
