// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#ifndef UI_PAGEHAUPTBILD_H
#define UI_PAGEHAUPTBILD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_pagehauptbild
extern void ui_pagehauptbild_screen_init(void);
extern void ui_pagehauptbild_screen_destroy(void);
extern lv_obj_t * ui_pagehauptbild;
extern lv_obj_t * ui_pnlsd;
extern lv_obj_t * ui_lblsd;
extern lv_obj_t * ui_imgsdok;
extern lv_obj_t * ui_imgsdeerror;
extern lv_obj_t * ui_pnlheader;
extern lv_obj_t * ui_pnlfooter;
extern lv_obj_t * ui_lblalarmline;
extern lv_obj_t * ui_pnlbuttonleiste;
extern lv_obj_t * ui_pnlmidleft;
extern lv_obj_t * ui_pnlmidright;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

