// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#include "ui.h"

lv_obj_t * ui_pagehauptbild = NULL;
lv_obj_t * ui_pnlsd = NULL;
lv_obj_t * ui_lblsd = NULL;
lv_obj_t * ui_imgsdok = NULL;
lv_obj_t * ui_imgsdeerror = NULL;
lv_obj_t * ui_pnlheader = NULL;
lv_obj_t * ui_pnlfooter = NULL;
lv_obj_t * ui_lblalarmline = NULL;
lv_obj_t * ui_pnlbuttonleiste = NULL;
lv_obj_t * ui_pnlmidleft = NULL;
lv_obj_t * ui_pnlmidright = NULL;
// event funtions

// build funtions

void ui_pagehauptbild_screen_init(void)
{
    ui_pagehauptbild = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_pagehauptbild, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pagehauptbild, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgroundlt);
    ui_object_set_themeable_style_property(ui_pagehauptbild, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgroundlt);

    ui_pnlsd = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlsd, 42);
    lv_obj_set_height(ui_pnlsd, 42);
    lv_obj_set_x(ui_pnlsd, 754);
    lv_obj_set_y(ui_pnlsd, 0);
    lv_obj_remove_flag(ui_pnlsd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlsd, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlsd, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblsd = lv_label_create(ui_pnlsd);
    lv_obj_set_width(ui_lblsd, 30);
    lv_obj_set_height(ui_lblsd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblsd, -14);
    lv_obj_set_y(ui_lblsd, 4);
    lv_label_set_long_mode(ui_lblsd, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_lblsd, "-----");
    ui_object_set_themeable_style_property(ui_lblsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_default);
    ui_object_set_themeable_style_property(ui_lblsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_default);
    lv_obj_set_style_text_align(ui_lblsd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblsd, &ui_font_Calibri12Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgsdok = lv_image_create(ui_pnlsd);
    lv_image_set_src(ui_imgsdok, &ui_img_leds_led_rs_green_l_png);
    lv_obj_set_width(ui_imgsdok, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgsdok, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_imgsdok, -8);
    lv_obj_set_y(ui_imgsdok, -14);
    lv_obj_remove_flag(ui_imgsdok, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_imgsdeerror = lv_image_create(ui_pnlsd);
    lv_image_set_src(ui_imgsdeerror, &ui_img_leds_led_rs_red_l_png);
    lv_obj_set_width(ui_imgsdeerror, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgsdeerror, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_imgsdeerror, -8);
    lv_obj_set_y(ui_imgsdeerror, -14);
    lv_obj_remove_flag(ui_imgsdeerror, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_pnlheader = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlheader, 746);
    lv_obj_set_height(ui_pnlheader, 42);
    lv_obj_set_x(ui_pnlheader, 4);
    lv_obj_set_y(ui_pnlheader, 0);
    lv_obj_remove_flag(ui_pnlheader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlheader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlheader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlheader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlheader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlheader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlfooter = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlfooter, 792);
    lv_obj_set_height(ui_pnlfooter, 44);
    lv_obj_set_x(ui_pnlfooter, 0);
    lv_obj_set_y(ui_pnlfooter, 217);
    lv_obj_set_align(ui_pnlfooter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlfooter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlfooter, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlfooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlfooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgrounddk);
    ui_object_set_themeable_style_property(ui_pnlfooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlfooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlfooter, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblalarmline = lv_label_create(ui_pnlfooter);
    lv_obj_set_width(ui_lblalarmline, 770);
    lv_obj_set_height(ui_lblalarmline, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblalarmline, -10);
    lv_obj_set_y(ui_lblalarmline, -9);
    lv_label_set_text(ui_lblalarmline, "");
    lv_obj_set_style_text_color(ui_lblalarmline, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblalarmline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblalarmline, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblalarmline, &ui_font_Calibri20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlbuttonleiste = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlbuttonleiste, 792);
    lv_obj_set_height(ui_pnlbuttonleiste, 64);
    lv_obj_set_x(ui_pnlbuttonleiste, 4);
    lv_obj_set_y(ui_pnlbuttonleiste, 369);
    lv_obj_remove_flag(ui_pnlbuttonleiste, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlbuttonleiste, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlbuttonleiste, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlbuttonleiste, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlbuttonleiste, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlbuttonleiste, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlbuttonleiste, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlmidleft = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlmidleft, 394);
    lv_obj_set_height(ui_pnlmidleft, 319);
    lv_obj_set_x(ui_pnlmidleft, 4);
    lv_obj_set_y(ui_pnlmidleft, 45);
    lv_obj_remove_flag(ui_pnlmidleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlmidleft, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlmidleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlmidleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlmidleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlmidleft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlmidleft, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlmidright = lv_obj_create(ui_pagehauptbild);
    lv_obj_set_width(ui_pnlmidright, 394);
    lv_obj_set_height(ui_pnlmidright, 319);
    lv_obj_set_x(ui_pnlmidright, 402);
    lv_obj_set_y(ui_pnlmidright, 45);
    lv_obj_remove_flag(ui_pnlmidright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlmidright, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pnlmidright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlmidright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backgroundlt);
    ui_object_set_themeable_style_property(ui_pnlmidright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_backgroundmed);
    ui_object_set_themeable_style_property(ui_pnlmidright, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_backgroundmed);
    lv_obj_set_style_border_width(ui_pnlmidright, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_pagehauptbild_screen_destroy(void)
{
    if(ui_pagehauptbild) lv_obj_del(ui_pagehauptbild);

    // NULL screen variables
    ui_pagehauptbild = NULL;
    ui_pnlsd = NULL;
    ui_lblsd = NULL;
    ui_imgsdok = NULL;
    ui_imgsdeerror = NULL;
    ui_pnlheader = NULL;
    ui_pnlfooter = NULL;
    ui_lblalarmline = NULL;
    ui_pnlbuttonleiste = NULL;
    ui_pnlmidleft = NULL;
    ui_pnlmidright = NULL;

}
