// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_default[1] = {0x99BDCC};
const ui_theme_variable_t _ui_theme_alpha_default[1] = {255};

const ui_theme_variable_t _ui_theme_color_backgroundlt[1] = {0x010824};
const ui_theme_variable_t _ui_theme_alpha_backgroundlt[1] = {255};

const ui_theme_variable_t _ui_theme_color_border[1] = {0x1488BA};
const ui_theme_variable_t _ui_theme_alpha_border[1] = {255};

const ui_theme_variable_t _ui_theme_color_backgroundmed[1] = {0x0E5D7E};
const ui_theme_variable_t _ui_theme_alpha_backgroundmed[1] = {255};

const ui_theme_variable_t _ui_theme_color_backgrounddk[1] = {0x000416};
const ui_theme_variable_t _ui_theme_alpha_backgrounddk[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

