// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Display

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_DEFAULT 0
#define UI_THEME_COLOR_BACKGROUNDLT 1
#define UI_THEME_COLOR_BORDER 2
#define UI_THEME_COLOR_BACKGROUNDMED 3
#define UI_THEME_COLOR_BACKGROUNDDK 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_default[1];
extern const ui_theme_variable_t _ui_theme_alpha_default[1];

extern const ui_theme_variable_t _ui_theme_color_backgroundlt[1];
extern const ui_theme_variable_t _ui_theme_alpha_backgroundlt[1];

extern const ui_theme_variable_t _ui_theme_color_border[1];
extern const ui_theme_variable_t _ui_theme_alpha_border[1];

extern const ui_theme_variable_t _ui_theme_color_backgroundmed[1];
extern const ui_theme_variable_t _ui_theme_alpha_backgroundmed[1];

extern const ui_theme_variable_t _ui_theme_color_backgrounddk[1];
extern const ui_theme_variable_t _ui_theme_alpha_backgrounddk[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
